/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm;


import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author mateo
 */
public class ATMpin extends javax.swing.JFrame {
       Connection con = null;
    PreparedStatement pst = null;
    /**
     * Creates new form ATMinside
     */
    public ATMpin() {
        initComponents();
        
        
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        Frametitile = new javax.swing.JPanel();
        ATMtitle = new javax.swing.JLabel();
        frametastiera = new javax.swing.JPanel();
        Buton1 = new javax.swing.JButton();
        Buton4 = new javax.swing.JButton();
        Buton3 = new javax.swing.JButton();
        Buton6 = new javax.swing.JButton();
        Buton2 = new javax.swing.JButton();
        Buton5 = new javax.swing.JButton();
        Buton7 = new javax.swing.JButton();
        Buton8 = new javax.swing.JButton();
        Buton9 = new javax.swing.JButton();
        Buton0 = new javax.swing.JButton();
        Butonclear = new javax.swing.JButton();
        Butonclear1 = new javax.swing.JButton();
        Butonenter = new javax.swing.JButton();
        entercardnr = new javax.swing.JTextField();
        inputcard = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        butonanash1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        butonanash2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        butonanash3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        butonanash4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        inputpin = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        butonanash5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        butonanash6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        butonanash7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        butonanash8 = new javax.swing.JPanel();
        butonround1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("ATMbackground"); // NOI18N

        Frametitile.setBackground(new java.awt.Color(153, 153, 153));
        Frametitile.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ATMtitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ATMtitle.setForeground(new java.awt.Color(255, 255, 255));
        ATMtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ATMtitle.setText("ATM");
        ATMtitle.setToolTipText("");
        ATMtitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout FrametitileLayout = new javax.swing.GroupLayout(Frametitile);
        Frametitile.setLayout(FrametitileLayout);
        FrametitileLayout.setHorizontalGroup(
            FrametitileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrametitileLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(ATMtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FrametitileLayout.setVerticalGroup(
            FrametitileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrametitileLayout.createSequentialGroup()
                .addComponent(ATMtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        frametastiera.setBackground(new java.awt.Color(153, 153, 153));

        Buton1.setText("1");
        Buton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton1MouseClicked(evt);
            }
        });
        Buton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buton1ActionPerformed(evt);
            }
        });

        Buton4.setText("4");
        Buton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton4MouseClicked(evt);
            }
        });

        Buton3.setText("3");
        Buton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton3MouseClicked(evt);
            }
        });

        Buton6.setText("6");
        Buton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton6MouseClicked(evt);
            }
        });

        Buton2.setText("2");
        Buton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton2MouseClicked(evt);
            }
        });

        Buton5.setText("5");
        Buton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton5MouseClicked(evt);
            }
        });

        Buton7.setText("7");
        Buton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton7MouseClicked(evt);
            }
        });

        Buton8.setText("8");
        Buton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton8MouseClicked(evt);
            }
        });

        Buton9.setText("9");
        Buton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton9MouseClicked(evt);
            }
        });

        Buton0.setText("0");
        Buton0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buton0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton0MouseClicked(evt);
            }
        });

        Butonclear.setBackground(new java.awt.Color(255, 204, 0));
        Butonclear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Butonclear.setForeground(new java.awt.Color(255, 255, 255));
        Butonclear.setText("Clear");
        Butonclear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Butonclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonclearMouseClicked(evt);
            }
        });
        Butonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonclearActionPerformed(evt);
            }
        });

        Butonclear1.setBackground(new java.awt.Color(255, 51, 51));
        Butonclear1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Butonclear1.setForeground(new java.awt.Color(255, 255, 255));
        Butonclear1.setText("Cancel");
        Butonclear1.setToolTipText("");
        Butonclear1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Butonclear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Butonclear1MouseClicked(evt);
            }
        });
        Butonclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butonclear1ActionPerformed(evt);
            }
        });

        Butonenter.setBackground(new java.awt.Color(0, 153, 51));
        Butonenter.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Butonenter.setForeground(new java.awt.Color(255, 255, 255));
        Butonenter.setText("Enter");
        Butonenter.setToolTipText("");
        Butonenter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Butonenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonenterMouseClicked(evt);
            }
        });
        Butonenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonenterActionPerformed(evt);
            }
        });

        entercardnr.setEditable(false);
        entercardnr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        entercardnr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entercardnr.setText("Enter Card");
        entercardnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entercardnrActionPerformed(evt);
            }
        });

        inputcard.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputcardFocusGained(evt);
            }
        });
        inputcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputcardActionPerformed(evt);
            }
        });
        inputcard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputcardKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputcardKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout frametastieraLayout = new javax.swing.GroupLayout(frametastiera);
        frametastiera.setLayout(frametastieraLayout);
        frametastieraLayout.setHorizontalGroup(
            frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frametastieraLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frametastieraLayout.createSequentialGroup()
                        .addGroup(frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Buton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buton7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Buton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buton0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Buton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buton9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Butonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Butonclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Butonenter, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frametastieraLayout.createSequentialGroup()
                        .addComponent(entercardnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputcard)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        frametastieraLayout.setVerticalGroup(
            frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frametastieraLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entercardnr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputcard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(frametastieraLayout.createSequentialGroup()
                            .addComponent(Buton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Buton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Buton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Buton0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(frametastieraLayout.createSequentialGroup()
                            .addGroup(frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Butonclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Buton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(frametastieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(frametastieraLayout.createSequentialGroup()
                                    .addComponent(Butonclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Butonenter, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(frametastieraLayout.createSequentialGroup()
                                    .addComponent(Buton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Buton9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(frametastieraLayout.createSequentialGroup()
                        .addComponent(Buton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGap(17, 17, 17))
        );

        butonanash1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/images/round.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout butonanash1Layout = new javax.swing.GroupLayout(butonanash1);
        butonanash1.setLayout(butonanash1Layout);
        butonanash1Layout.setHorizontalGroup(
            butonanash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butonanash1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        butonanash1Layout.setVerticalGroup(
            butonanash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, butonanash1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        butonanash2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/images/round.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout butonanash2Layout = new javax.swing.GroupLayout(butonanash2);
        butonanash2.setLayout(butonanash2Layout);
        butonanash2Layout.setHorizontalGroup(
            butonanash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butonanash2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        butonanash2Layout.setVerticalGroup(
            butonanash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, butonanash2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        butonanash3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/images/round.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout butonanash3Layout = new javax.swing.GroupLayout(butonanash3);
        butonanash3.setLayout(butonanash3Layout);
        butonanash3Layout.setHorizontalGroup(
            butonanash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butonanash3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        butonanash3Layout.setVerticalGroup(
            butonanash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, butonanash3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        butonanash4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/images/round.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout butonanash4Layout = new javax.swing.GroupLayout(butonanash4);
        butonanash4.setLayout(butonanash4Layout);
        butonanash4Layout.setHorizontalGroup(
            butonanash4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butonanash4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        butonanash4Layout.setVerticalGroup(
            butonanash4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, butonanash4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        inputpin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        inputpin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputpin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputpinFocusGained(evt);
            }
        });
        inputpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputpinKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputpinKeyTyped(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 102, 204));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("PIN");
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputpin)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputpin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        butonanash5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/images/round.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout butonanash5Layout = new javax.swing.GroupLayout(butonanash5);
        butonanash5.setLayout(butonanash5Layout);
        butonanash5Layout.setHorizontalGroup(
            butonanash5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butonanash5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );
        butonanash5Layout.setVerticalGroup(
            butonanash5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, butonanash5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        butonanash6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/images/round.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout butonanash6Layout = new javax.swing.GroupLayout(butonanash6);
        butonanash6.setLayout(butonanash6Layout);
        butonanash6Layout.setHorizontalGroup(
            butonanash6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butonanash6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        butonanash6Layout.setVerticalGroup(
            butonanash6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, butonanash6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        butonanash7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/images/round.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout butonanash7Layout = new javax.swing.GroupLayout(butonanash7);
        butonanash7.setLayout(butonanash7Layout);
        butonanash7Layout.setHorizontalGroup(
            butonanash7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butonanash7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        butonanash7Layout.setVerticalGroup(
            butonanash7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, butonanash7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        butonanash8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        butonround1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/images/round.png"))); // NOI18N
        butonround1.setText("jLabel1");

        javax.swing.GroupLayout butonanash8Layout = new javax.swing.GroupLayout(butonanash8);
        butonanash8.setLayout(butonanash8Layout);
        butonanash8Layout.setHorizontalGroup(
            butonanash8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butonanash8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butonround1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        butonanash8Layout.setVerticalGroup(
            butonanash8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butonanash8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butonround1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butonanash4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonanash3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonanash1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonanash2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butonanash8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonanash7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonanash6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonanash5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butonanash1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butonanash2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butonanash3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butonanash4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(butonanash5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butonanash6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butonanash7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butonanash8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frametastiera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Frametitile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Frametitile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frametastiera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int a=0;

    private void Buton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buton1ActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_Buton1ActionPerformed

    private void Buton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton1MouseClicked

        
{
    if(a==1)
        {
            
          inputpin.setText(inputpin.getText()+"1");
        
        }
    else if(a==2)
        {
           if(inputcard.getText().length()==4)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           else if(inputpin.getText().length()>=4)
           {
               inputpin.setText(inputpin.getText().substring(0,4));
           }
           
           else if(inputcard.getText().length()==8)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
           
          else if(inputcard.getText().length()==12)
            
           {
              inputcard.setText(inputpin.getText().substring(0,11));
           }
           
            inputcard.setText(inputcard.getText()+"1");
           
        }
    
}
        
      // TODO add your handling code here:
    }//GEN-LAST:event_Buton1MouseClicked

    private void Buton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton2MouseClicked
{
    if(a==1)
        {
            
          inputpin.setText(inputpin.getText()+"2");
        
        }
    else if(a==2)
        {
           if(inputcard.getText().length()==4)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           else if(inputpin.getText().length()>=4)
           {
               inputpin.setText(inputpin.getText().substring(0,3));
           }
           
           else if(inputcard.getText().length()==8)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
           
          else if(inputcard.getText().length()==12)
            
           {
              inputcard.setText(inputpin.getText().substring(0,11));
           }
           
            inputcard.setText(inputcard.getText()+"2");
           
        }
    
}
// TODO add your handling code here:
    }//GEN-LAST:event_Buton2MouseClicked

    private void Buton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton3MouseClicked
{
    if(a==1)
        {
            
          inputpin.setText(inputpin.getText()+"3");
        
        }
    else if(a==2)
        {
           if(inputcard.getText().length()==4)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           else if(inputpin.getText().length()>=4)
           {
               inputpin.setText(inputpin.getText().substring(0,3));
           }
           
           else if(inputcard.getText().length()==8)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
           
          else if(inputcard.getText().length()==12)
            
           {
              inputcard.setText(inputpin.getText().substring(0,11));
           }
           
            inputcard.setText(inputcard.getText()+"3");
           
        }
    
}// TODO add your handling code here:
    }//GEN-LAST:event_Buton3MouseClicked

    private void Buton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton4MouseClicked
{
    if(a==1)
        {
            
          inputpin.setText(inputpin.getText()+"4");
        
        }
    else if(a==2)
        {
           if(inputcard.getText().length()==4)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           else if(inputpin.getText().length()>=4)
           {
               inputpin.setText(inputpin.getText().substring(0,3));
           }
           
           else if(inputcard.getText().length()==8)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
           
          else if(inputcard.getText().length()==12)
            
           {
              inputcard.setText(inputpin.getText().substring(0,11));
           }
           
            inputcard.setText(inputcard.getText()+"4");
           
        }
    
}// TODO add your handling code here:
    }//GEN-LAST:event_Buton4MouseClicked

    private void Buton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton5MouseClicked
{
    
    if(a==1)
        {
            
          inputpin.setText(inputpin.getText()+"5");
        
        }
    else if(a==2)
        {
           if(inputcard.getText().length()==4)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           else if(inputpin.getText().length()>=4)
           {
               inputpin.setText(inputpin.getText().substring(0,3));
           }
           
           else if(inputcard.getText().length()==8)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
           
          else if(inputcard.getText().length()==12)
            
           {
              inputcard.setText(inputpin.getText().substring(0,11));
           }
           
            inputcard.setText(inputcard.getText()+"5");
           
        }
    
}// TODO add your handling code here:
    }//GEN-LAST:event_Buton5MouseClicked

    private void Buton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton6MouseClicked
{
    if(a==1)
        {
            
          inputpin.setText(inputpin.getText()+"6");
        
        }
    else if(a==2)
        {
           if(inputcard.getText().length()==4)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           else if(inputpin.getText().length()>=4)
           {
               inputpin.setText(inputpin.getText().substring(0,3));
           }
           
           else if(inputcard.getText().length()==8)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
           
          else if(inputcard.getText().length()==12)
            
           {
              inputcard.setText(inputpin.getText().substring(0,11));
           }
           
            inputcard.setText(inputcard.getText()+"6");
           
        }
    
}// TODO add your handling code here:
    }//GEN-LAST:event_Buton6MouseClicked

    private void Buton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton7MouseClicked
{
    if(a==1)
        {
            
          inputpin.setText(inputpin.getText()+"7");
        
        }
    else if(a==2)
        {
           if(inputcard.getText().length()==4)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           else if(inputpin.getText().length()>=4)
           {
               inputpin.setText(inputpin.getText().substring(0,3));
           }
           
           else if(inputcard.getText().length()==8)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
           
          else if(inputcard.getText().length()==12)
            
           {
              inputcard.setText(inputpin.getText().substring(0,11));
           }
           
            inputcard.setText(inputcard.getText()+"7");
           
        }
    
}// TODO add your handling code here:
    }//GEN-LAST:event_Buton7MouseClicked

    private void Buton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton8MouseClicked
{
    if(a==1)
        {
            
          inputpin.setText(inputpin.getText()+"8");
        
        }
    else if(a==2)
        {
           if(inputcard.getText().length()==4)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           else if(inputpin.getText().length()>=4)
           {
               inputpin.setText(inputpin.getText().substring(0,3));
           }
           
           else if(inputcard.getText().length()==8)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
           
          else if(inputcard.getText().length()==12)
            
           {
              inputcard.setText(inputpin.getText().substring(0,11));
           }
           
            inputcard.setText(inputcard.getText()+"8");
           
        }
    
}// TODO add your handling code here:
    }//GEN-LAST:event_Buton8MouseClicked

    private void Buton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton9MouseClicked
{
    if(a==1)
        {
            
          inputpin.setText(inputpin.getText()+"9");
        
        }
    else if(a==2)
        {
           if(inputcard.getText().length()==4)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           else if(inputpin.getText().length()>=4)
           {
               inputpin.setText(inputpin.getText().substring(0,3));
           }
           
           else if(inputcard.getText().length()==8)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
           
          else if(inputcard.getText().length()==12)
            
           {
              inputcard.setText(inputpin.getText().substring(0,11));
           }
           
            inputcard.setText(inputcard.getText()+"9");
           
        }
    
}// TODO add your handling code here:
    }//GEN-LAST:event_Buton9MouseClicked

    private void Buton0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton0MouseClicked
{
    if(a==1)
        {
          inputpin.setText(inputpin.getText()+"0");
        
        }
        else if(a==2)
        {
           if(inputcard.getText().length()==4)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
           
           else if(inputcard.getText().length()==8)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
           
          else if(inputcard.getText().length()==12)
            
           {
              inputcard.setText(inputcard.getText()+" ");
           }
           
            inputcard.setText(inputcard.getText()+"0");
           
        }
    
}// TODO add your handling code here:
    }//GEN-LAST:event_Buton0MouseClicked
 private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {
    
 }
    
    private void ButonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonclearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButonclearActionPerformed

    private void ButonclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonclearMouseClicked
inputpin.setText(""); 
inputcard.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ButonclearMouseClicked

    private void Butonclear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Butonclear1MouseClicked
        this.setVisible(false);
        new ChooseBankATM().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Butonclear1MouseClicked

    private void Butonclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butonclear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Butonclear1ActionPerformed

    private void ButonenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonenterMouseClicked
            
        if(inputpin.getText().isEmpty() || inputpin.getText().equals(0)){
            JOptionPane.showMessageDialog(null,"Enter Valid Pin");
       }else if(inputcard.getText().isEmpty() || inputcard.getText().equals(0)){
                           JOptionPane.showMessageDialog(null,"Enter Valid Card");
                }else{
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url ="jdbc:sqlserver://localhost\\MSSQLSERVER01:1433;databaseName=KlientATM; trustServerCertificate=true; user = SA; password = 123";
            Connection con = DriverManager.getConnection(url);
            String sql = "Select * from klient where card=? and pin=?";
            PreparedStatement pst = con.prepareStatement(sql);
            

            pst.setString(1,inputcard.getText());
            pst.setString(2, inputpin.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                int id=rs.getInt("accountNo");
                String Query = "Select  = "+(id)+" from klient where name = ? and card =?";
            pst = con.prepareStatement(Query);
            
                JOptionPane.showMessageDialog(null, "Login sucessful. Your ID is : "+(id));
                
            
      
                InsideATM s= new InsideATM();
                s.setVisible(true);
                setVisible(false);
            }else{
                        JOptionPane.showMessageDialog(null, "Login unsucessful");
                        }
            // TODO add your handling code here:
            }                
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
       }
                 
           // TODO add your handling code here:
    }//GEN-LAST:event_ButonenterMouseClicked

    private void ButonenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButonenterActionPerformed

    private void entercardnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entercardnrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entercardnrActionPerformed

    private void inputpinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputpinKeyPressed
        boolean max = inputpin.getText().length() > 3;
    if ( max ){
        evt.consume();
    }// TODO add your handling code here:
    }//GEN-LAST:event_inputpinKeyPressed

    private void inputpinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputpinFocusGained
   a=1;     // TODO add your handling code here:
    }//GEN-LAST:event_inputpinFocusGained

    private void inputpinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputpinKeyTyped
    boolean max = inputpin.getText().length() > 3;
    if ( max ){
        evt.consume();
    }           // TODO add your handling code here:
    }//GEN-LAST:event_inputpinKeyTyped

    private void inputcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputcardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputcardActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void inputcardFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputcardFocusGained
a=2;        // TODO add your handling code here:
    }//GEN-LAST:event_inputcardFocusGained

    private void inputcardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputcardKeyTyped
        boolean max = inputcard.getText().length() > 11;
    if ( max ){
        evt.consume();
    }// TODO add your handling code here:
    }//GEN-LAST:event_inputcardKeyTyped

    private void inputcardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputcardKeyPressed
      boolean max = inputcard.getText().length() > 11;
    if ( max ){
        evt.consume();
    }  // TODO add your handling code here:
    }//GEN-LAST:event_inputcardKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMpin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ATMtitle;
    private javax.swing.JButton Buton0;
    private javax.swing.JButton Buton1;
    private javax.swing.JButton Buton2;
    private javax.swing.JButton Buton3;
    private javax.swing.JButton Buton4;
    private javax.swing.JButton Buton5;
    private javax.swing.JButton Buton6;
    private javax.swing.JButton Buton7;
    private javax.swing.JButton Buton8;
    private javax.swing.JButton Buton9;
    private javax.swing.JButton Butonclear;
    private javax.swing.JButton Butonclear1;
    private javax.swing.JButton Butonenter;
    private javax.swing.JPanel Frametitile;
    private javax.swing.JPanel butonanash1;
    private javax.swing.JPanel butonanash2;
    private javax.swing.JPanel butonanash3;
    private javax.swing.JPanel butonanash4;
    private javax.swing.JPanel butonanash5;
    private javax.swing.JPanel butonanash6;
    private javax.swing.JPanel butonanash7;
    private javax.swing.JPanel butonanash8;
    private javax.swing.JLabel butonround1;
    private javax.swing.JTextField entercardnr;
    private javax.swing.JPanel frametastiera;
    private javax.swing.JTextField inputcard;
    private javax.swing.JTextField inputpin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    
}
